CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  uptime VARCHAR(20) DEFAULT '99.9%',
  duration VARCHAR(100) DEFAULT '',
  description TEXT DEFAULT '',
  detail TEXT DEFAULT '',
  image VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
